### PR TITLE
Merging the dev branch

### PR DESCRIPTION
**Pull request by Gobot1234**
@somespecialone You might be interested in preparing for the changes here

Small changelog:
- Add an example for how to use a Casket.
- Rip the enums from CSGO source leak like ItemQuality, ItemFlags and ItemOrigin.
- Add BackpackItem.rename_to + BackpackItem.delete.
- Make Caskets actually work reliably.
- Stop spamming wait_fors in logs.
- Implement Matches, not had full time to test this.
- Fetch the backpack much less.

### CODE REVIEW

**Comment by somespecialone** [comment]
Oh, thanks! Actually i want to propose some small changes but not sure if i can add it to youe pull request (really don't know how to do it if possible). `Paint.seed`, `Paint.index` and `Sticker.tint_id` is integer, not float. `Sticker.slot` can be 0-4 (not sure about 4, never seen this value on sticker, but hear something and somewhere that it is possible). Nothing to say about related changes, i think your work really good!

**Comment by Gobot1234** [comment]
> Sticker.slot can be 0-4 (not sure about 4, never seen this value on sticker, but hear something and somewhere that it is possible)

Do you know what the numbers correspond to, I'd like to put them in an Enum indeally?

**Comment by somespecialone** [comment]
> Do you know what the numbers correspond to, I'd like to put them in an Enum indeally?
Correspond to nothing. Or correspond to itself. Number just mean in which slot(0, 1, 2, 3, **4?**) on weapon(and sticker item) 
sticker kit has been applied.

**Comment by Gobot1234** [comment]
> > Do you know what the numbers correspond to, I'd like to put them in an Enum indeally?
> 
> Correspond to nothing. Or correspond to itself. Number just mean in which slot(0, 1, 2, 3, **4?**) on weapon(and sticker item) 
> 
> sticker kit has been applied.

Do the slots have names or is it just a number?

**Comment by somespecialone** [comment]
> Do the slots have names or is it just a number?

No, i mean haven't

**Pull request merged**
